print("hello,world!")
print("I am from a branch!")
# print("how merge branch")
print('修复了一个bug')
print("how merge branch")
print("我是从删除的分支里出来的")
print('test stash')
print("很不错,修复完bug回来干活了,活干完了,提交!")

# print('又有了一个bug')
print('bug被修复了')
